package com.salesforce.crmmembench

import com.salesforce.crmmembench.conversations.ConversationGenerator
import com.salesforce.crmmembench.questions.evidence._
import com.salesforce.crmmembench.questions.evidence.generators._
import org.scalatest.funsuite.AnyFunSuite

/**
 * Test class for examining the final prompts generated by evidence generators.
 * This class helps understand what prompts are passed to the LLM for generation.
 */
class TestConversationGeneratorPrompts extends AnyFunSuite {

  // Conversation generator for building full prompts
  val conversationGenerator = new ConversationGenerator()

  // Sample persona for testing
  val testPerson = Personas.Person(
    id = "test-person",
    category = "Professional",
    role_name = "Software Engineer",
    description = "Senior software engineer specializing in backend systems",
    background = Some("I'm a senior software engineer with 8 years of experience building scalable backend systems. I work primarily with Java and Python, and I'm passionate about system architecture and performance optimization.")
  )

  // Sample use case for testing
  val testUseCase = EvidenceUseCase(
    id = 1,
    category = "Professional Life",
    scenario_description = "The software engineer discusses their favorite programming language and explains why they prefer it over others."
  )

  // Sample evidence core for testing
  val testEvidenceCore = GeneratedEvidenceCore(
    question = "What programming language do you prefer and why?",
    answer = "Python, because of its simplicity and readability",
    message_evidences = List(
      Message(speaker = "User", text = "I prefer Python for its simplicity and readability"),
      Message(speaker = "User", text = "Java is great for enterprise applications but can be verbose")
    )
  )


  test("UserFactsEvidenceGenerator - Final Conversation Prompt") {
    val generator = new UserFactsEvidenceGenerator(evidenceCount = 2)
    val conversationPromptParts = generator.getConversationPromptParts(testPerson, testUseCase, testEvidenceCore)
    val fullPrompt = conversationGenerator.getFullConversationPrompt(testPerson, conversationPromptParts)
    
    println("="*80)
    println("MULTI-EVIDENCE GENERATOR - FULL CONVERSATION PROMPT")
    println("="*80)
    println(fullPrompt)
    println("="*80)
    
    assert(conversationPromptParts.evidenceCount == 2)
    assert(fullPrompt.contains("user facts"))
    assert(fullPrompt.contains("Software Engineer"))
    assert(fullPrompt.contains("Python"))
  }

  test("ChangingEvidenceGenerator - Final Conversation Prompt") {
    val generator = new ChangingEvidenceGenerator(evidenceCount = 2)
    val changingEvidenceCore = testEvidenceCore.copy(
      question = "What travel plans do I have?",
      answer = "No travel plans, the Paris trip was cancelled",
      message_evidences = List(
        Message(speaker = "User", text = "I'm planning to visit Paris next month"),
        Message(speaker = "User", text = "My Paris trip got cancelled due to work")
      )
    )
    
    val conversationPromptParts = generator.getConversationPromptParts(testPerson, testUseCase, changingEvidenceCore)
    val fullPrompt = conversationGenerator.getFullConversationPrompt(testPerson, conversationPromptParts)
    
    println("="*80)
    println("CHANGING EVIDENCE GENERATOR - FULL CONVERSATION PROMPT")
    println("="*80)
    println(fullPrompt)
    println("="*80)
    
    assert(fullPrompt.contains("changing evidence"))
    assert(fullPrompt.contains("temporal progression"))
    assert(fullPrompt.contains("Paris"))
    assert(fullPrompt.contains("Software Engineer"))
  }

  test("AbstentionEvidenceGenerator - Final Conversation Prompt") {
    val generator = new AbstentionEvidenceGenerator(evidenceCount = 2)
    val abstentionEvidenceCore = testEvidenceCore.copy(
      question = "What is John's phone number?",
      answer = "There is no information in prior conversations to answer this question",
      message_evidences = List(
        Message(speaker = "User", text = "John works in the marketing department"),
        Message(speaker = "User", text = "John joined the company last month")
      )
    )
    
    val conversationPromptParts = generator.getConversationPromptParts(testPerson, testUseCase, abstentionEvidenceCore)
    val fullPrompt = conversationGenerator.getFullConversationPrompt(testPerson, conversationPromptParts)
    
    println("="*80)
    println("ABSTENTION EVIDENCE GENERATOR - FULL CONVERSATION PROMPT")
    println("="*80)
    println(fullPrompt)
    println("="*80)
    
    assert(fullPrompt.contains("abstention"))
    assert(fullPrompt.contains("NOT available"))
    assert(fullPrompt.contains("John"))
    assert(fullPrompt.contains("Software Engineer"))
  }

  test("AssistantFactsEvidenceGenerator - Final Conversation Prompt") {
    val generator = new AssistantFactsEvidenceGenerator(evidenceCount = 2)
    val assistantFactsEvidenceCore = testEvidenceCore.copy(
      question = "What tools did you recommend for deployment?",
      answer = "Docker and Jenkins",
      message_evidences = List(
        Message(speaker = "Assistant", text = "I would recommend using Docker for containerization"),
        Message(speaker = "Assistant", text = "I suggest implementing CI/CD with Jenkins")
      )
    )
    
    val conversationPromptParts = generator.getConversationPromptParts(testPerson, testUseCase, assistantFactsEvidenceCore)
    val fullPrompt = conversationGenerator.getFullConversationPrompt(testPerson, conversationPromptParts)
    
    println("="*80)
    println("ASSISTANT FACTS EVIDENCE GENERATOR - FULL CONVERSATION PROMPT")
    println("="*80)
    println(fullPrompt)
    println("="*80)
    
    assert(fullPrompt.contains("assistant facts"))
    assert(fullPrompt.contains("Assistant"))
    assert(fullPrompt.contains("Docker"))
    assert(fullPrompt.contains("Software Engineer"))
  }

}