package com.salesforce.crmmembench

import com.salesforce.crmmembench.questions.evidence.generators._
import com.salesforce.crmmembench.questions.evidence.EvidenceUseCase
import com.salesforce.crmmembench.Personas
import org.scalatest.funsuite.AnyFunSuite

/**
 * Test class for examining the evidence core prompts generated by evidence generators.
 * This class helps understand what prompts are passed to the LLM for evidence core generation.
 */
class TestEvidenceCorePrompts extends AnyFunSuite {

  // Sample persona for testing
  val testPerson = Personas.Person(
    id = "test-person",
    category = "Professional",
    role_name = "Software Engineer",
    description = "Senior software engineer specializing in backend systems",
    background = Some("I'm a senior software engineer with 8 years of experience building scalable backend systems. I work primarily with Java and Python, and I'm passionate about system architecture and performance optimization.")
  )

  // Sample use case for testing
  val testUseCase = EvidenceUseCase(
    id = 1,
    category = "Professional Life",
    scenario_description = "The software engineer discusses their favorite programming language and explains why they prefer it over others."
  )
  val evidenceCount = 1
  test("UserFactsEvidenceGenerator - Evidence Core Prompt") {
    val generator = new UserFactsEvidenceGenerator(evidenceCount)
    val prompt = generator.getEvidenceCorePrompt(testPerson, testUseCase)
    
    println("="*80)
    println("USER FACTS EVIDENCE GENERATOR - EVIDENCE CORE PROMPT")
    println("="*80)
    println(prompt)
    println("="*80)
    
    assert(prompt.nonEmpty)
  }

  test("ChangingEvidenceGenerator - Evidence Core Prompt") {
    val changingUseCase = testUseCase.copy(
      scenario_description = "The software engineer initially mentions using one programming language but later switches to another."
    )
    
    val generator = new ChangingEvidenceGenerator(evidenceCount)
    val prompt = generator.getEvidenceCorePrompt(testPerson, changingUseCase)
    
    println("="*80)
    println("CHANGING EVIDENCE GENERATOR - EVIDENCE CORE PROMPT")
    println("="*80)
    println(prompt)
    println("="*80)
    
    assert(prompt.nonEmpty)
  }

  test("AbstentionEvidenceGenerator - Evidence Core Prompt") {
    val abstentionUseCase = testUseCase.copy(
      scenario_description = "The software engineer mentions programming languages but never specifies their salary."
    )
    
    val generator = new AbstentionEvidenceGenerator(evidenceCount)
    val prompt = generator.getEvidenceCorePrompt(testPerson, abstentionUseCase)
    
    println("="*80)
    println("ABSTENTION EVIDENCE GENERATOR - EVIDENCE CORE PROMPT")
    println("="*80)
    println(prompt)
    println("="*80)
    
    assert(prompt.nonEmpty)
  }

  test("AssistantFactsEvidenceGenerator - Evidence Core Prompt") {
    val assistantFactsUseCase = testUseCase.copy(
      scenario_description = "The software engineer asks for advice and the assistant provides recommendations."
    )
    
    val generator = new AssistantFactsEvidenceGenerator(evidenceCount)
    val prompt = generator.getEvidenceCorePrompt(testPerson, assistantFactsUseCase)
    
    println("="*80)
    println("ASSISTANT FACTS EVIDENCE GENERATOR - EVIDENCE CORE PROMPT")
    println("="*80)
    println(prompt)
    println("="*80)
    
    assert(prompt.nonEmpty)
  }

}